### ISSUE TITLE
very cool but not working here

### ISSUE THREAD

**Issue by davephillips** [Djack13/VCV-Rack-Csound-Modules#1]
Linux Fedora 23
Rack 0.5.x

Wonderful to see a Csound-based module ! Your plugin builds without problems, but I'm not getting any effected sound. The Bypass works, I can hear the plain sound from a simple VCO, but I get no reverb with the effect active. Perhaps I'm too early in the testing ? At any rate, please take this as a note of encouragement, and I hope you plan more Csound-based modules.

**Comment by Djack13** [comment]
Thanks for your encouragement,
My Rack version is 0.5.1 builds on Mint.
You can enable the csound message in csoundReverb.cpp line 20 and start Rack on a terminal to see what happends to csound.

**Comment by davephillips** [comment]
I've enabled the print function, I get a huge number of these warnings:

WARNING: Csound not ready for performance: csoundStart() has not been called

So many are generated that I'm unable to scroll back to the start. But does that warning give you any hint what I'm missing ?

**Comment by davephillips** [comment]
Hey, your update works here now, thanks to this error message:

--Csound version 6.10.1 (double samples) Jan  6 2018 
[commit: c6018b58fa8bcc9997ba446515cb8b3cb9729052]
libsndfile-1.0.27
realtime mode enabled
UnifiedCSD:  ./plugins/Csound/src/CsoundReverb.csd   <----------
Reading CSD failed ... stopping
Csound csd compilation error!

You should probably mention to builders that the cloned directory needs to be named Csound, i.e.  'git clone https://github.com/Djack13/VCV-Rack-Csound-Modules.git Csound'. That will create the expected directory. I changed the directory name, the module works now. The sound is choppy at first, but switching to Bypass and back again smooths it out. The reverb is excellent, Sean did a nice job with it.

Muchas gracias ! :)

**Comment by Djack13** [comment]
Happy to read you :)
Thanks a lot for testing and finding my stupid mistake  (i am new to git too)

Merci beaucoup :)
